// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: actutltype_rpc.proto
// Original file comments:
// protoc  --cpp_out=. .\actutltype_rpc.proto
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_actutltype_5frpc_2eproto__INCLUDED
#define GRPC_actutltype_5frpc_2eproto__INCLUDED

#include "actutltype_rpc.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

// The greeting service definition.
class Device final {
 public:
  static constexpr char const* service_full_name() {
    return "Device";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::GetDeviceReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetDeviceReply>> AsyncGetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetDeviceReply>>(AsyncGetDeviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetDeviceReply>> PrepareAsyncGetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GetDeviceReply>>(PrepareAsyncGetDeviceRaw(context, request, cq));
    }
    virtual ::grpc::Status SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::SetDeviceReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetDeviceReply>> AsyncSetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetDeviceReply>>(AsyncSetDeviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetDeviceReply>> PrepareAsyncSetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetDeviceReply>>(PrepareAsyncSetDeviceRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GetDeviceReply>* AsyncGetDeviceRaw(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GetDeviceReply>* PrepareAsyncGetDeviceRaw(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SetDeviceReply>* AsyncSetDeviceRaw(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SetDeviceReply>* PrepareAsyncSetDeviceRaw(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::GetDeviceReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetDeviceReply>> AsyncGetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetDeviceReply>>(AsyncGetDeviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetDeviceReply>> PrepareAsyncGetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GetDeviceReply>>(PrepareAsyncGetDeviceRaw(context, request, cq));
    }
    ::grpc::Status SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::SetDeviceReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetDeviceReply>> AsyncSetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetDeviceReply>>(AsyncSetDeviceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetDeviceReply>> PrepareAsyncSetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetDeviceReply>>(PrepareAsyncSetDeviceRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetDevice(::grpc::ClientContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SetDevice(::grpc::ClientContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GetDeviceReply>* AsyncGetDeviceRaw(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GetDeviceReply>* PrepareAsyncGetDeviceRaw(::grpc::ClientContext* context, const ::GetDeviceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SetDeviceReply>* AsyncSetDeviceRaw(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SetDeviceReply>* PrepareAsyncSetDeviceRaw(::grpc::ClientContext* context, const ::SetDeviceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetDevice_;
    const ::grpc::internal::RpcMethod rpcmethod_SetDevice_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetDevice(::grpc::ServerContext* context, const ::GetDeviceRequest* request, ::GetDeviceReply* response);
    virtual ::grpc::Status SetDevice(::grpc::ServerContext* context, const ::SetDeviceRequest* request, ::SetDeviceReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDevice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDevice(::grpc::ServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDevice(::grpc::ServerContext* context, ::GetDeviceRequest* request, ::grpc::ServerAsyncResponseWriter< ::GetDeviceReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetDevice() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDevice(::grpc::ServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetDevice(::grpc::ServerContext* context, ::SetDeviceRequest* request, ::grpc::ServerAsyncResponseWriter< ::SetDeviceReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetDevice<WithAsyncMethod_SetDevice<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetDevice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::GetDeviceRequest, ::GetDeviceReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::GetDeviceRequest* request, ::GetDeviceReply* response) { return this->GetDevice(context, request, response); }));}
    void SetMessageAllocatorFor_GetDevice(
        ::grpc::experimental::MessageAllocator< ::GetDeviceRequest, ::GetDeviceReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GetDeviceRequest, ::GetDeviceReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDevice(::grpc::ServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetDevice(
      ::grpc::CallbackServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetDevice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SetDevice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::SetDeviceRequest, ::SetDeviceReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::SetDeviceRequest* request, ::SetDeviceReply* response) { return this->SetDevice(context, request, response); }));}
    void SetMessageAllocatorFor_SetDevice(
        ::grpc::experimental::MessageAllocator< ::SetDeviceRequest, ::SetDeviceReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SetDeviceRequest, ::SetDeviceReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDevice(::grpc::ServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetDevice(
      ::grpc::CallbackServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetDevice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetDevice<ExperimentalWithCallbackMethod_SetDevice<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetDevice<ExperimentalWithCallbackMethod_SetDevice<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDevice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDevice(::grpc::ServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetDevice() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDevice(::grpc::ServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDevice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDevice(::grpc::ServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDevice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetDevice() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDevice(::grpc::ServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetDevice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetDevice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDevice(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDevice(::grpc::ServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetDevice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetDevice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SetDevice() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetDevice(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDevice(::grpc::ServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetDevice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetDevice(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDevice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GetDeviceRequest, ::GetDeviceReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GetDeviceRequest, ::GetDeviceReply>* streamer) {
                       return this->StreamedGetDevice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDevice(::grpc::ServerContext* /*context*/, const ::GetDeviceRequest* /*request*/, ::GetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDevice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GetDeviceRequest,::GetDeviceReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetDevice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetDevice() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SetDeviceRequest, ::SetDeviceReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SetDeviceRequest, ::SetDeviceReply>* streamer) {
                       return this->StreamedSetDevice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetDevice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetDevice(::grpc::ServerContext* /*context*/, const ::SetDeviceRequest* /*request*/, ::SetDeviceReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetDevice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SetDeviceRequest,::SetDeviceReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetDevice<WithStreamedUnaryMethod_SetDevice<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetDevice<WithStreamedUnaryMethod_SetDevice<Service > > StreamedService;
};


#endif  // GRPC_actutltype_5frpc_2eproto__INCLUDED
